### ISSUE TITLE
Native GPU on M1 Macs

### ISSUE THREAD

**Issue by tedsecretsource** [sonoisa/arm64-docker-pytorch-tensorflow#1]
This is really just a question: does the resulting image access the native GPUs on M1 Macs? In other words, can I use this image to train models on an M1 Mac?

**Comment by sonoisa** [comment]
Unfortunately, the M1 Mac GPU is not available in Docker containers.
This is because in order to use Mac GPUs, you need the Metal API, which is not available in Docker (Linux OS).
