### ISSUE TITLE
How to build image for M2 96GB

### ISSUE THREAD

**Issue by elcolie** [sonoisa/arm64-docker-pytorch-tensorflow#2]
I am using M2 OSX 13.2. Python 3.11.1
How can I build docker image that enable `MPS` + `PyTorch`

```bash
To build on 64GB M1 Max MacBook Pro
Make sure to allocate 48GB of memory and 8 cpu to Docker.
$ ./build.sh --build-type full --jobs 8 --bazel_memory_limit 24576
```

**Comment by sonoisa** [comment]
Please see https://github.com/sonoisa/arm64-docker-pytorch-tensorflow/issues/1#issuecomment-1382653203 .
